---
db:
  host: "db"
  user: "postgres"
  password: "sprinkler"
  dbname: "postgres"
  sslmode: "disable"

orchard:
  address: ":8082"

control:
  address: ":8080"
  trustedProxies:
    - "0.0.0.0/0"
    - "::/0"
  apiKey: "changeme"

scheduler:
  interval: "1s"
  lockTimeout: "1h"
  orchard:
    address: "http://ws:8082"
    # apiKeyName: "x-api-key"
    # apiKey: "changeme"

# configs for static credentials or role arn to assume
# aws:
#   clientRegion: "changeme"
#   staticCredentials:
#     awsAccessKeyId: "changeme"
#     awsSecretKey: "changeme"
#     sessionToken: "changeme"
#   assumeRoleArn: "changeme"
...
